--- 
- 
  hosts: localhost
  connection: local
  name: "Ansible test"
  tasks: 
    - name: "launching AWS instance using Ansible"
      ec2: 
        assign_public_ip: true
        count: 1
        group: default
        image: ami-0b44050b2d893d5f7
        instance_type: t2.micro
        key_name: aws_instance_ansible
        region: ap-south-1
        vpc_subnet_id: subnet-4a012422
        wait: yes
